from enum import StrEnum


class Verdict(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"


class Reason(StrEnum):
    IN_SCOPE_VALIDATED = "IN_SCOPE_VALIDATED"
    SAFE_CONVERSATIONAL_INPUT = "SAFE_CONVERSATIONAL_INPUT"
    EMPTY_INPUT = "EMPTY_INPUT"
    INVALID_INPUT_TYPE = "INVALID_INPUT_TYPE"
    INPUT_LIMIT_EXCEEDED = "INPUT_LIMIT_EXCEEDED"
    INVALID_OR_SUSPICIOUS_UNICODE = "INVALID_OR_SUSPICIOUS_UNICODE"
    FORBIDDEN_CONTROL_PATTERN = "FORBIDDEN_CONTROL_PATTERN"
    OUT_OF_SCOPE_SEMANTIC_DISTANCE = "OUT_OF_SCOPE_SEMANTIC_DISTANCE"
    OUT_OF_SCOPE_CONTRASTIVE_MARGIN = "OUT_OF_SCOPE_CONTRASTIVE_MARGIN"
    MIXED_SCOPE_DETECTED = "MIXED_SCOPE_DETECTED"
    AMBIGUOUS_OR_MISSING_CONTEXT = "AMBIGUOUS_OR_MISSING_CONTEXT"
